#!/usr/bin/env sh

cmd_release() {

  local action="$1"; shift

  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  if [[ "$action" != "start" ]] && ! echo $BRANCH | grep --quiet -E '^release/'; then
    echo "Cannot find release name in current branch $BRANCH"
    exit 1
  fi
  NAME=$(echo $BRANCH | sed 's/.*\///')
  IAMADMIN=$(i_am_admin)

  case $action in
      "start")
          git flow release start "$@"
          ;;
      "publish")
          git flow release publish "$@"
          ;;
      "propose")
        git flow release publish $NAME
        merge_request $BRANCH "master" "release $NAME" "false"
          ;;
      "finish")
        set -e
        if [[ "$IAMADMIN" == "true" ]]; then
          pull "master"
          git tag -a $NAME
          git push --tags
          git checkout develop
          git merge --no-ff $NAME
          git push origin develop
          git branch -d $BRANCH
        else
          pull "master"
          pull "develop"
          echo "Deleting release (should be merged)"
          git branch -d $BRANCH
          echo "Pulling tags"
          git pull --tags
        fi
        ;;
      *)
        echo "Unknown action $action"
        exit 1
        ;;
  esac
}
