#!/usr/bin/env sh

cmd_config() {
  git flow config

  PID=$(get_gitlab_prid)
  echo "Gitlab ProjectID: $PID"
  if git config --get gitplow.gitlab.token > /dev/null; then
    echo "Gitlab Token: [local]"
  else
    echo "Gitlab Token: [global]"
  fi
  DOMAIN=$(get_gitlab_domain)
  if git config --get gitplow.gitlab.token > /dev/null; then
    echo "Gitlab Domain: $DOMAIN [local]"
  else
    echo "Gitlab Domain: $DOMAIN [global]"
  fi
  PROTOCOL=$(get_gitlab_protocol)
  if git config --get gitplow.gitlab.protocol > /dev/null; then
    echo "Gitlab Protocol: $PROTOCOL [local]"
  else
    echo "Gitlab Protocol: $PROTOCOL [global]"
  fi
}
