#!/usr/bin/env sh

cmd_feature() {

  local action="$1"; shift

  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  if [[ "$action" != "start" ]] && ! echo $BRANCH | grep --quiet -E '^feature/'; then
    echo "Cannot find feature name in current branch $BRANCH"
    exit 1
  fi
  NAME=$(echo $BRANCH | sed 's/.*\///')
  IAMADMIN=$(i_am_admin)


  case $action in
      "start")
          git flow feature start "$@"
          ;;
      "publish")
          git flow feature publish "$@"
          ;;
      "propose")
          git flow feature publish $NAME
          merge_request $BRANCH "develop" "feature $NAME" "false"
          ;;
      "finish")
        set -e
        if [[ "$IAMADMIN" == "true" ]]; then
          pull "develop"
          echo "Deleting feature (should be merged)"
          git branch -d $BRANCH
        else
          pull "develop"
          echo "Deleting feature (should be merged)"
          git branch -d $BRANCH
        fi
        ;;
      *)
        exit 1
        ;;
  esac
}
