#!/usr/bin/env sh

cmd_hotfix() {

  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  NAME=$(echo $BRANCH | sed 's/.*\///')

  local action="$1"; shift

  case $action in
      "start")
          git flow hotfix start "$@"
          ;;
      "publish")
          git flow hotfix publish "$@"
          ;;
      "finish")
        git flow hotfix publish $NAME

        merge_request $BRANCH "master" "hotfix $NAME" "false"
          ;;
      "complete")
        set -e
        pull "master"
        pull "develop"
        echo "Deleting release (should be merged)"
        git branch -d $BRANCH
        echo "Pulling tags"
        git pull --tags
        ;;
      "approved")
        pull "master"
        git tag -e $NAME
        git push --tags
        git checkout develop
        git merge --no-ff $NAME
        git push origin develop
        git branch -d $BRANCH
        ;;
      *)
        exit 1
        ;;
  esac
}
