#!/usr/bin/env sh

cmd_release() {

  BRANCH=$(git rev-parse --abbrev-ref HEAD --)
  NAME=$(echo $BRANCH | sed 's/.*\///')

  local action="$1"; shift

  case $action in
      "start")
          git flow release start "$@"
          ;;
      "finish")
        git flow release pull $NAME
        git flow release publish $NAME

        merge_request $BRANCH "develop" "release $name" "false"
        merge_request $BRANCH "master" "release $name" "false"
          ;;
      "complete")
        set -e
        pull "master"
        pull "develop"
        echo "Deleting release (should be merged)"
        git branch -d $BRANCH
        echo "Pulling tags"
        git pull --tags
        ;;
      "approve")
        approveMasterDevelop "$NAME" "$1" "$2"
        ;;
      *)
        echo "Unknown action $action"
        exit 1
        ;;
  esac
}
