#!/usr/bin/env sh

cmd_release() {

  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  NAME=$(echo $BRANCH | sed 's/.*\///')

  local action="$1"; shift

  case $action in
      "start")
          git flow release start "$@"
          ;;
      "publish")
          git flow release publish "$@"
          ;;
      "finish")
        git flow release publish $NAME

        merge_request $BRANCH "master" "release $NAME" "false"
          ;;
      "complete")
        set -e
        pull "master"
        pull "develop"
        echo "Deleting release (should be merged)"
        git branch -d $BRANCH
        echo "Pulling tags"
        git pull --tags
        ;;
      "approved")
        pull "master"
        git tag $NAME -e
        git push --tags
        git checkout develop
        git merge --no-ff $NAME
        git push origin develop
        git branch -d $BRANCH
        ;;
      *)
        echo "Unknown action $action"
        exit 1
        ;;
  esac
}
