#!/usr/bin/env sh

cmd_hotfix() {

  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  if ! echo $BRANCH | grep --quiet -E '^hotfix/'; then
    echo "Cannot find hotfix name in current branch $BRANCH"
    exit 1
  fi
  NAME=$(echo $BRANCH | sed 's/hotfix\///')
  IAMADMIN=$(i_am_admin)

  local action="$1"; shift

  case $action in
      "start")
          git flow hotfix start "$@"
          ;;
      "publish")
          git flow hotfix publish "$@"
          ;;
      "propose")
        git flow hotfix publish $NAME

        merge_request $BRANCH "master" "hotfix $NAME" "false"
          ;;
      "finish")
        set -e
        if [[ "$IAMADMIN" == "true" ]]; then
          pull "master"
          git tag -a $NAME
          git push --tags
          git checkout develop
          git merge --no-ff $NAME
          git push origin develop
          git branch -d $BRANCH
          git checkout master
        else
          pull "master"
          pull "develop"
          echo "Deleting release (should be merged)"
          git branch -d $BRANCH
          echo "Pulling tags"
          git pull --tags
        fi
        ;;
      *)
        exit 1
        ;;
  esac
}
