#!/usr/bin/env sh

cmd_feature() {

  PROJECTID=$(get_gitlab_prid)
  PRIVATETOKEN=$(get_gitlab_token)

  BRANCH=$(git rev-parse --abbrev-ref HEAD --)
  NAME=$(echo $BRANCH | sed 's/.*\///')

  local action="$1"; shift

  case $action; in
      "start")
          git flow feature start "$@"
          ;;
      "finish")
        PROJECTID=$1
        PRIVATETOKEN=$2
        BRANCH=$3
        HOTFIXNAME=$4
        git flow feature pull $NAME
        git flow feature publish $NAME

        merge_request $PROJECTID $PRIVATETOKEN $BRANCH "develop" \
          "feature $name" "false"
          ;;
      "complete")
        set -e
        echo "Pulling develop"
        git checkout develop
        git pull origin develop
        echo "Deleting feature (should be merged)"
        git branch -d $BRANCH
        ;;
      *)
        exit 1
        ;;
  esac
}
