#!/usr/bin/env sh

cmd_feature() {

  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  NAME=$(echo $BRANCH | sed 's/.*\///')

  local action="$1"; shift

  case $action in
      "start")
          git flow feature start "$@"
          ;;
      "publish")
          git flow feature publish "$@"
          ;;
      "finish")
        git flow feature publish $NAME

        merge_request $BRANCH "develop" "feature $name" "false"
          ;;
      "complete" | "approved")
        set -e
        pull "develop"
        echo "Deleting feature (should be merged)"
        git branch -d $BRANCH
        ;;
      *)
        exit 1
        ;;
  esac
}
